config/routes.rb
Rails.application.routes.draw do
  root 'recipe_lists#index'

  resources :recipe_lists do
    member do
      delete :remove_recipe, path: "remove_recipe/:recipe_id"
    end
  end

  resources :recipes do
    resources :items do
      collection do
        post :create_multiple, path: "create_multiple"
      end
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_and_belongs_to_many :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_and_belongs_to_many :items
  has_and_belongs_to_many :recipe_lists
end

app/models/recipe_list.rb
class RecipeList < ApplicationRecord
  has_and_belongs_to_many :recipes
  has_many :items, through: :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def edit
    recipe = Recipe.find(params[:recipe_id])
    @item = recipe.items.find(params[:id])
  end

  def create
    recipe = Recipe.find(params[:recipe_id])
    item = recipe.items.create(item_params)
    redirect_to recipe_path(@recipe)
  end

  def update
    recipe = Recipe.find(params[:recipe_id])
    item = recipe.items.find(params[:id])
    item.update(item_params)
    redirect_to recipe_path(recipe)
  end

  def destroy
    recipe = Recipe.find(params[:recipe_id])
    item = recipe.items.find(params[:id])
    item.destroy
    redirect_to recipe_path(recipe)
  end

  def create_multiple
    recipe = Recipe.find(params[:recipe_id])

    params[:items].each_line chomp: true do |line|
      quantity, name = line.split "#"

      if name == nil
        name = quantity
        quantity = ""
      end

      quantity.strip!
      name.strip!
      item = recipe.items.create quantity: quantity, name: name
    end

    redirect_to recipe_path(recipe)
  end

  private
    def item_params
      params.require(:item).permit(:name, :quantity)
    end
end

app/controllers/recipe_lists_controller.rb
class RecipeListsController < ApplicationController
  before_action :set_recipe_list, only: [:show, :edit, :update, :destroy, :remove_recipe]

  # GET /recipe_lists
  # GET /recipe_lists.json
  def index
    @recipe_lists = RecipeList.all
  end

  # GET /recipe_lists/1
  # GET /recipe_lists/1.json
  def show
  end

  # GET /recipe_lists/new
  def new
    @recipe_list = RecipeList.new
  end

  # GET /recipe_lists/1/edit
  def edit
  end

  # POST /recipe_lists
  # POST /recipe_lists.json
  def create
    @recipe_list = RecipeList.new(recipe_list_params)
    @recipe_list.recipe_ids = params[:recipe_ids]

    respond_to do |format|
      if @recipe_list.save
        format.html { redirect_to @recipe_list, notice: 'Recipe list was successfully created.' }
        format.json { render :show, status: :created, location: @recipe_list }
      else
        format.html { render :new }
        format.json { render json: @recipe_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipe_lists/1
  # PATCH/PUT /recipe_lists/1.json
  def update
    # Update the recipes contained by this list
    @recipe_list.recipe_ids = params[:recipe_ids]

    respond_to do |format|
      if @recipe_list.update(recipe_list_params)
        format.html { redirect_to @recipe_list, notice: 'Recipe list was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe_list }
      else
        format.html { render :edit }
        format.json { render json: @recipe_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_lists/1
  # DELETE /recipe_lists/1.json
  def destroy
    @recipe_list.destroy
    respond_to do |format|
      format.html { redirect_to recipe_lists_url, notice: 'Recipe list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Remove recipe from recipe list
  def remove_recipe
    recipe = Recipe.find(params[:recipe_id])
    @recipe_list.recipes.delete(recipe)

    respond_to do |format|
      format.html { redirect_to @recipe_list, notice: 'Recipe was removed.' }
      format.json { render :show, status: :ok, location: @recipe_list }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe_list
      @recipe_list = RecipeList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_list_params
      params.require(:recipe_list).permit(:name)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    # Delete the items first
    @recipe.items.destroy_all
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/recipe_lists_helper.rb
module RecipeListsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/edit.html.erb
<%= form_with(model: @ingredient, url: recipe_ingredient_path(@ingredient)) do |form| %>
  <%= render 'shared/form_errors', item: @ingredient, item_name: "ingredient" %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%= form_with(model: @item, url: recipe_item_path(@item)) do |form| %>
  <%= render 'shared/form_errors', item: @item, item_name: "item" %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipe_lists/_form.html.erb
<%= form_with(model: recipe_list, local: true) do |form| %>
  <% if recipe_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe_list.errors.count, "error") %> prohibited this recipe_list from being saved:</h2>

      <ul>
        <% recipe_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <% Recipe.all.each do |recipe|
         is_checked = recipe_list.recipes.exists? recipe.id
    %>
      <div class="chosen-recipe">
        <label><%= recipe.name %>
          <%= check_box_tag "recipe_ids[]", recipe.id, is_checked %>
        </label>
        <%= link_to 'Goto', recipe_path(recipe), data: { confirm: 'Are you sure? (You will lose unsaved edits)' }  %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_lists/edit.html.erb
<h1>Editing Recipe List</h1>

<%= render 'form', recipe_list: @recipe_list %>

<%= link_to 'Show', @recipe_list %> |
<%= link_to 'Back', recipe_lists_path %>

app/views/recipe_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipe Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipe_lists.each do |recipe_list| %>
      <tr>
        <td><%= recipe_list.name %></td>
        <td><%= link_to 'Show', recipe_list %></td>
        <td><%= link_to 'Destroy', recipe_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe List', new_recipe_list_path %> |
<%= link_to 'Show all Recipes', recipes_path %>

app/views/recipe_lists/new.html.erb
<h1>New Recipe List</h1>

<%= render 'form', recipe_list: @recipe_list %>

<%= link_to 'Back', recipe_lists_path %>

app/views/recipe_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe_list.name %>
</p>

<h2>Recipes</h2>
<ul>
<% @recipe_list.recipes.each do |recipe| %>
  <li>
    <%= recipe.name %>
    <%= link_to 'Remove', remove_recipe_recipe_list_path(@recipe_list, recipe_id: recipe),
                          method: :delete %>
  </li>
<% end %>
</ul>

<h2>Ingredients</h2>
<% @recipe_list.recipes.each do |recipe| %>
  <h3><%= recipe.name %></h3>
  <ol>
  <% recipe.items.each do |item| %>
    <li>
      <%= item.quantity %> <%= item.name %>
    </li>
  <% end %>
  </ol>
<% end %>

<%= link_to 'Edit', edit_recipe_list_path(@recipe_list) %> |
<%= link_to 'Back', recipe_lists_path %>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <%= render 'shared/form_errors', item: recipe, item_name: "recipe" %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %> |
<%= link_to 'Show Recipe Lists', recipe_lists_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<h2>Ingredients</h2>
<ul>
<% @recipe.items.each do |item| %>
  <li>
    <%= item.quantity %> <%= item.name %>
    <%= link_to 'Edit', edit_recipe_item_path(@recipe, item) %>
    <%= link_to 'Delete', recipe_item_path(@recipe, item), method: :delete %>
  </li>
<% end %>
</ul>

<h2>Add ingredient:</h2>
<%= form_with(model: [ @recipe, @recipe.items.build ]) do |form| %>
  <p>
    <%= form.label :quantity %><%= form.text_field :quantity %>
  </p>
  <p>
    <%= form.label :name %><%= form.text_field :name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<h2>Add multiple ingredients</h2>
<p>One per line, quantity and name separated by # (e.g. "1 tsp # sugar")</p>
<%= form_with(url: create_multiple_recipe_items_path(@recipe),
              method: :post) do %>
  <%= text_area_tag :items %><br>
  <%= submit_tag "Submit" %>
<% end %>

<br><br>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>

app/views/shared/_form_errors.html.erb
<% if item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this <%= item_name %> from being saved:</h2>

    <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>